#!/bin/bash
if [ $# -eq 2 ]; then
    python3 Clients/getnewtoken.py $1 "$2"
else
    echo "Formato incorrecto. Por favor indique los valores correspondientes"
    echo "./get_new_token <usuario> <'proxy_servicio_de_autentificación'>"
fi