#!/bin/bash
#este scriptintentará  subir  un  nuevo  mapa. Los  argumentos  que  recibirá serán los siguientes: <proxy servicio mapas> <token> <archivo mapa>
python3 Clients/client_room_managment.py -p "$1" $2 $3